### ISSUE TITLE
Builds crash on TravisCI ... errors blame OpenMX

### ISSUE THREAD

**Issue by chrisaberson** [OpenMx/OpenMx#203]
Can't get a clean build on linux for my package due to issue with OpenMX -error shown below

* installing *source* package ‘OpenMx’ ...
** package ‘OpenMx’ successfully unpacked and MD5 sums checked
** using staged installation
NOTE: ./configure is not an autoconf generated script.
Change default C/C++ compiler and default compile flags by editing ~/.R/Makevars
** libs
Error in .shlib_internal(args) :
C++14 standard requested but CXX14 is not defined
* removing ‘/home/travis/R/Library/OpenMx’
* restoring previous ‘/home/travis/R/Library/OpenMx’
Error in i.p(...) :
(converted from warning) installation of package ‘OpenMx’ had non-zero exit status

**Comment by RMKirkpatrick** [comment]
For the record, OP is posting this issue per my [advice on Facebook](https://www.facebook.com/robert.m.kirkpatrick.5/posts/10220077434548620?comment_id=10220091993832593&comment_tracking=%7B%22tn%22%3A%22R%22%7D).

Good night.

**Comment by jpritikin** [comment]
Add one of `util/gcc?.conf` to `~/.R/Makevars` and try again.

**Comment by chrisaberson** [comment]
Not understanding your comment. I don't have a file or directory called .R/Makevars

Could you provide an example of what this fix might look like?

**Comment by jpritikin** [comment]
> I don't have a file or directory called .R/Makevars

Yeah, you need to create it. Try `mkdir $HOME/.R`

Then `cp util/gcc7.conf $HOME/.R/Makevars`

**Comment by chrisaberson** [comment]
Thanks - any suggestions on where and  how to place that in my travis.yml file doing it as shown below doesn't fly. 

language: r
cache: packages
os: 
  - linux
sudo: false
dist: trusty
before_install:
 - sudo apt install libgsl-dev
 - mkdir $HOME/.R
 - cp util/gcc7.conf $HOME/.R/Makevars

**Comment by jpritikin** [comment]
Wait, why are you building OpenMx on Travis?

You could see how we do it, https://travis-ci.org/OpenMx/OpenMx/builds

**Comment by chrisaberson** [comment]
I'm building my own package which has a downstream dependency for OpenMX which is causing it to fail on Linux. Windows and Mac are fine but since the last update, my Linux builds fail and point toward OpenMX as the reason.

**Comment by jpritikin** [comment]
Ah ha! OpenMx takes forever to build. You'll have better luck using a binary package. Try,

```
install:
- sudo apt-get install -yq --allow-unauthenticated --no-install-suggests --no-install-recommends r-cran-OpenMx
```

**Comment by mikewlcheung** [comment]
I also recently have the same issue in checking metaSEM, which depends on OpenMx.

Maybe I have incorrectly set other things, the suggestion does not work for me. My .travis.yml is https://travis-ci.org/mikewlcheung/metasem/builds/540537767/config

Any suggestions? Thanks in advance.

**Comment by mcneale** [comment]
Is it because we changed our travis site?  It’s hard to think of what else could have changed, and the error is could not find...

**Comment by jpritikin** [comment]
The package name is all lowercase. Worked here, `https://travis-ci.org/jpritikin/metasem/jobs/540707636`

**Comment by jpritikin** [comment]
@chrisaberson BTW, which package do you develop?

**Comment by mikewlcheung** [comment]
Thanks, Joshua.

Changing OpenMx to openmx worked in the R Release.

**Comment by mcneale** [comment]
Glad it’s fixed!  What might be done to avoid similar issues in future?

**Comment by jpritikin** [comment]
> What might be done to avoid similar issues in future?

The solution I proposed will continue to work for the foreseeable future.

**Comment by chrisaberson** [comment]
@jpritikin https://github.com/chrisaberson/pwr2ppl - I should be submitting to CRAN this week. 

The change with openmx in lower case build successfully now. Thank you for all your help. I'm completely new to the Linux environment, so this has been a bit challenging.

**Comment by jpritikin** [comment]
Hey, are you aware of the OpenMx function [mxPowerSearch](https://vipbg.vcu.edu/vipbg/OpenMx2/docs//OpenMx/latest/_static/Rdoc/mxPower.html)?

**Comment by chrisaberson** [comment]
Wasn't aware of that! That looks very useful. Thanks for pointing it out.

**Comment by cdriveraus** [comment]
Adding this fix basically doubled my build time for ctsem on travis using linux...

**Comment by tbates** [comment]
Slyer builds surprise me, @cdriveraus: They should be much *quicker* now: OpenMx takes Travis over an 2-hours to compile, AFAIK, whereas a non-compiled downstream like `umx` takes ~15minutes. So using binaries for OpenMx and all our dependencies should be faster for you.

What's your `.travis.yml`?

**Comment by cdriveraus** [comment]
The only confounding factor is that since it was suggested I also included rstan using the same approach, the issue seems to be more that there's a whole bunch of R setup going on that I don't think was before... 
```
language: r
sudo: false
cache: packages
  
r_check_args: "--no-vignettes"
r_build_args: '--no-build-vignettes'

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      r: devel
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
 #   - os: linux
  #    dist: trusty
 #     r: release
 #     addons:
 #       apt:
  #        sources:
   #         - ubuntu-toolchain-r-test
  #          - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
  #            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
  #        packages:
 #           - clang-7
   #   env:
  #      - MATRIX_EVAL="CC=clang-7 CXX=clang++-7"
    - os: osx
      osx_image: xcode10
      r: release
      fortran: false

     
before_install:
  - mkdir -p ~/.R/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CXX14 = clang++ -arch x86_64 -ftemplate-depth-256" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CXX14FLAGS = -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-unknown-pragmas" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CC = clang" >> ~/.R/Makevars; fi
  - eval "${MATRIX_EVAL}"
  
install:
  #- R -e 'devtools::install_deps(dep = T)'
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -yq --allow-unauthenticated --no-install-suggests --no-install-recommends r-cran-openmx; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -yq --allow-unauthenticated --no-install-suggests --no-install-recommends r-cran-rstan; fi

script:
  - travis_wait 30 R CMD build --no-build-vignettes .
  - travis_wait 30 R CMD check --no-build-vignettes --as-cran  *tar.gz

```

**Comment by jpritikin** [comment]
@cdriveraus The `.travis.yml` looks reasonable. I'm really surprised that binary packages would take longer than compiling. Are you sure it wasn't just variance in the travis nodes? Sometimes travis is fast and sometimes slow depending on unpredictable factors.

**Comment by cdriveraus** [comment]
May be so, I guess we'll see how things go, I only semi understand travis but one thought is that perhaps with the previous approach it was only having to compile once? I vaguely remember builds after an error / significant change taking much longer...

**Comment by tbates** [comment]
yes, as you had `cache: packages` then anything unchanged would run fast from the cache

**Comment by cdriveraus** [comment]
I remember that line now :) So I'll see if build times drop back to something like they used to, or else suggestions for fixing compiling would be welcome...

**Comment by cdriveraus** [comment]
build times seem a little better than their original state (9 mins today, 12 was a rough average before), so the suggestions that travis was just having a bad day seem correct. Thanks.

**Comment by cdriveraus** [comment]
Trying to work around a new bit of travis excitement:

> * checking package dependencies ... ERROR
> Packages required but not available:
>   'rstantools', 'data.table', 'mize', 'pkgbuild', 'cOde', 'Deriv'
> Packages suggested but not available:
>   'knitr', 'testthat', 'devtools', 'DEoptim', 'GGally', 'shiny'
> Package required and available but unsuitable version: ‘rstan’

, I found I had to add:
`- R -e 'install.packages("remotes");library(remotes);remotes::install_deps(dependencies = TRUE,upgrade="always")'`
in the before install section, or else a whole lot of dependencies are unavailable. But then this tries to install openmx and things break again.  So it's a somewhat related zombie issue, I'd really appreciate any ideas :) :)

**Comment by jpritikin** [comment]
Do you use?

```
export _R_CHECK_FORCE_SUGGESTS_=false
```

?

**Comment by cdriveraus** [comment]
I tried true at some point, but have that line commented out at present.

```
language: r
sudo: false
#cache: packages
  
r_check_args: "--no-vignettes"
r_build_args: '--no-build-vignettes'

#repos:
#  CRAN: https://cloud.r-project.org
#  ropensci: http://packages.ropensci.org
  
env:
global:
  - R_MAX_NUM_DLLS=999
  #- _R_CHECK_FORCE_SUGGESTS_=true
  - _R_CHECK_CRAN_INCOMING_=true
  - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      r_binary_packages:
        - rstantools
        - data.table
        - jsonlite
        - Rcpp
        - cOde
        - remotes
        - Deriv
        - mvtnorm
        - knitr
        - testthat
        - devtools
        - DEoptim
        - GGally
        - shiny
        - mize
        - StanHeaders
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      r: devel
      r_binary_packages:
        - remotes
        - rstantools
        - data.table
        - jsonlite
        - Rcpp
        - cOde
        - Deriv
        - mvtnorm
        - knitr
        - testthat
        - devtools
        - DEoptim
        - GGally
        - shiny
        - mize
        - StanHeaders
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
 #   - os: linux
  #    dist: trusty
 #     r: release
 #     addons:
 #       apt:
  #        sources:
   #         - ubuntu-toolchain-r-test
  #          - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
  #            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
  #        packages:
 #           - clang-7
   #   env:
  #      - MATRIX_EVAL="CC=clang-7 CXX=clang++-7"
    - os: osx
      osx_image: xcode10
      r: release
      r_binary_packages:
        - rstantools
        - data.table
        - jsonlite
        - Rcpp
        - OpenMx
        - cOde
        - remotes
        - Deriv
        - mvtnorm
        - knitr
        - testthat
        - devtools
        - DEoptim
        - GGally
        - shiny
        - mize
        - StanHeaders
      fortran: false

     
before_install:
  - mkdir -p ~/.R/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14 += g++-7 -fPIC -std=c++1y" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CXX14 = clang++ -arch x86_64 -ftemplate-depth-256" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CXX14FLAGS = -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-unknown-pragmas" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CC = clang" >> ~/.R/Makevars; fi
  - R -e 'install.packages("remotes");library(remotes);remotes::install_deps(dependencies = TRUE,upgrade="always")'
  - eval "${MATRIX_EVAL}"
  
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -yq --allow-unauthenticated --no-install-suggests --no-install-recommends r-cran-openmx; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -yq --allow-unauthenticated --no-install-suggests --no-install-recommends r-cran-rstan; fi

script:
  - travis_wait 30 R CMD build --no-build-vignettes .
  - travis_wait 30 R CMD check --no-build-vignettes --as-cran  *tar.gz

```
